baseURL = 'https://pajamy.github.io/hida-takayama-high-school-clone'
languageCode = 'ja-JP'
title = 'My New Hugo Site'

[params]
	customCSS = ['css/base.css', 'css/header.css', 'css/footer.css', 'css/output.css']